//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4pBotTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4pBotTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Main&quot;: [
        ///    {
        ///      &quot;topic_id&quot;: 273633,
        ///      &quot;first_post&quot;: {
        ///        &quot;id&quot;: 1267467,
        ///        &quot;time&quot;: 1467539465,
        ///        &quot;user&quot;: {
        ///          &quot;id&quot;: 77635,
        ///          &quot;name&quot;: &quot;Stang&quot;,
        ///          &quot;photo_url&quot;: null,
        ///          &quot;reputation&quot;: 0
        ///        }
        ///      },
        ///      &quot;last_post&quot;: {
        ///        &quot;id&quot;: 1267525,
        ///        &quot;time&quot;: 1467558798,
        ///        &quot;user&quot;: {
        ///          &quot;id&quot;: 48325,
        ///          &quot;name&quot;: &quot;Th0ru5&quot;,
        ///          &quot;photo_url&quot;: null,
        ///          &quot;reputation&quot;: 20
        ///        }
        ///      },
        ///      &quot;fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4pJson {
            get {
                return ResourceManager.GetString("4pJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Main&quot;: [
        ///    {
        ///      &quot;topic_id&quot;: 273633,
        ///      &quot;first_post&quot;: {
        ///        &quot;id&quot;: 1267467,
        ///        &quot;time&quot;: 1467539465,
        ///        &quot;user&quot;: {
        ///          &quot;id&quot;: 77635,
        ///          &quot;name&quot;: &quot;Stang&quot;,
        ///          &quot;photo_url&quot;: null,
        ///          &quot;reputation&quot;: 0
        ///        }
        ///      },
        ///      &quot;last_post&quot;: {
        ///        &quot;id&quot;: 1267525,
        ///        &quot;time&quot;: 1467558798,
        ///        &quot;user&quot;: {
        ///          &quot;id&quot;: 48325,
        ///          &quot;name&quot;: &quot;Th0ru5&quot;,
        ///          &quot;photo_url&quot;: null,
        ///          &quot;reputation&quot;: 20
        ///        }
        ///      },
        ///      &quot;fo [rest of string was truncated]&quot;;.
        /// </summary>
  
    }
}
