// This file has been generated by the GUI designer. Do not modify.

using Gtk;
using Mono.Unix;

namespace pBot
{
    public partial class MainWindow
    {
        private Button button2;

        protected virtual void Build()
        {
            Gui.Initialize(this);
            // Widget MainWindow
            Name = "MainWindow";
            Title = Catalog.GetString("MainWindow");
            WindowPosition = (WindowPosition) 4;
            // Container child MainWindow.Gtk.Container+ContainerChild
            button2 = new Button();
            button2.CanFocus = true;
            button2.Name = "button2";
            button2.UseUnderline = true;
            button2.Label = Catalog.GetString("GtkButton");
            Add(button2);
            if (Child != null)
            {
                Child.ShowAll();
            }
            DefaultWidth = 400;
            DefaultHeight = 300;
            Show();
            DeleteEvent += OnDeleteEvent;
        }
    }
}