
// This file has been generated by the GUI designer. Do not modify.

namespace pBot
{
    public partial class  MainWindow
    {
        private global::Gtk.Button button2;

        protected virtual void Build()
        {
            global::pBot.Gui.Initialize(this);
            // Widget MainWindow
            this.Name = "MainWindow";
            this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child MainWindow.Gtk.Container+ContainerChild
            this.button2 = new global::Gtk.Button();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseUnderline = true;
            this.button2.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
            this.Add(this.button2);
            if ((this.Child != null))
            {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
